apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "folding-at-home.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "folding-at-home.labels" . | nindent 4 }}
data:
  config.xml: |
    <config>
      <!--
        To set your user name, team and passkey just edit the text
        in quotes below.
      -->

      <!-- User Information -->
      <user value="{{ .Values.username }}"/>         <!-- Enter your user name here -->
      <team value="{{ .Values.team }}"/>         <!-- Your team number -->
      <passkey value="{{ .Values.passkey }}"/>      <!-- 32 hexadecimal characters if provided -->

      <power value="full"/>    <!-- Throttling this at K8s level -->
      <gpu value="false"/>      <!-- If true, attempt to autoconfigure GPUs -->
      <fold-anon value="{{- if .Values.username -}}false{{- else -}}true{{- end -}}"/>
    </config>
