apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mprime.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mprime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mprime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mprime.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /root
          command:
            - sh
            - "-c"
            - |
              /bin/sh << 'EOF'
              # exit when any command fails
              set -e
              cp /root/prime.txt /prime.txt
              echo "ComputerID=$(hostname)" > /local.txt
              echo "WorkerThreads={{ .Values.workersPerReplica }}" >> /local.txt
              echo "Memory={{ .Values.memoryMB }} during 7:30-23:30 else {{ .Values.memoryMB }}" >> /local.txt
              ./mprime -d
              EOF
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ include "mprime.fullname" . }}
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ include "mprime.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
