apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xmrig.fullname" . }}
  labels:
    {{- include "xmrig.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xmrig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xmrig.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          command:
            - ./xmrig
            - --donate-level
            - '{{ .Values.poolDonationPercent }}'
            - --max-cpu-usage
            - '95'
            - -o
            - {{ .Values.pool }}
            - -u
            - {{ .Values.email }}
            - -p
            - {{ .Values.password }}
            - -k
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
